name: test
on:
  workflow_dispatch: #Esto nos permite ejecutar el workflow desde el menu actions de github.
  push:              #Ejecuta el workflow cuando se hace un push en la branch main.
    branches:
      - main  
  pull_request:      #Ejecuta el workflow cuando se hace un pull request de la branch main.
    branches:
      - main         

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Copiar codigo #Procura una copia del codigo que se encuentra en el repositorio sobre la cual trabajar en el workflow.
      uses: actions/checkout@v2
    
    - name: Preparar JDK #Prepara el Java Development Kit a utilizar para las pruebas.
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Compile
      run: javac -cp "lib/*" mercadotech/src/test/ProductoTest.java mercadotech/src/main/Producto.java

    - name: Run Unit Tests
      run: java -cp "lib/*:mercadotech/src/test" org.junit.platform.console.ConsoleLauncher --scan-class-path --details=tree
      
    - name: Mensaje de Listo 
      run: echo "Listas las pruebas maestro!!"
